name: 🚀 Deploy website on push

on:
  push:
    branches: [main]   # Change 'main' if your branch is named differently

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 📦 Build site
        run: |
          npm ci
          npm run build
      - name: 📂 Sync dist folder to public_html via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./dist/
